version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
          - post_db

  ui:
    container_name: ui-service
    image: ${USERNAME}/ui:${UI_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
    depends_on:
      - post
    ports:
      - ${UI_PORT}:9292/tcp
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - front_net

  post:
    container_name: post-service
    image: ${USERNAME}/post:${POST_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - back_net
      - front_net

  comment:
    container_name: comment-service
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net


volumes:
  post_db:

networks:
  back_net:
  front_net:
