{
 "title": "ui_service_monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "env", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "UI HTTP Requests",
   "type": "graph",
   "description": "UI HTTP Requests recieved",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{kubernetes_namespace=\"$namespace\"}[1m])"
    }
   ]
  },
  {
   "title": "Error requests rate",
   "type": "graph",
   "description": "Error requests rate",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP response time",
   "type": "graph",
   "description": "HTTP response time 95th percentile",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(ui_request_latency_seconds_bucket[5m])) by (le))"
    }
   ]
  }
 ]
}